### ISSUE TITLE
Doesn't work with Ansible 2.10.3

### ISSUE THREAD

**Issue by laptevn** [lean-delivery/ansible-role-oracle-db#17]
##### SUMMARY
2.10.3 version of Ansible finds this [variable](https://github.com/lean-delivery/ansible-role-oracle-db/blob/master/tasks/oraInst/readOra.yml#L14) defined with invalid name.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
No idea what you need here. You already have all required details.

##### ANSIBLE VERSION
```
2.10.3
```

##### CONFIGURATION
Nothing

##### OS / ENVIRONMENT
MacOS 10.15.6

##### STEPS TO REPRODUCE
1. Run `ansible-galaxy install lean_delivery.oracle_db`
2. Run the following playbook:
```
---
- name: Install Oracle
  hosts: oracle
  roles:
    - role: lean_delivery.oracle_db
      oracle_version: xe
      transport_web: http://download.xskernel.org/soft/linux-rpm/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
      oracle_images:
        - oracle-xe-11.2.0-1.0.x86_64.rpm.zip
      sid: xe
      systempassword: "{{ lookup('env', 'ORACLE_PASSWORD') }}"
```
3. Get the following error:
`TASK [lean_delivery.oracle_db : Get value of install_group] ********************
skipping: [qa191.blujay.global] => (item=inventory_loc=/u01/app/oraInventory) 
failed: [qa191.blujay.global] (item=inst_group=oinstall) => {"ansible_loop_var": "item", "changed": false, "item": "inst_group=oinstall", "msg": "The variable name 'oracledb.install_group' is not valid. Variables must start with a letter or underscore character, and contain only letters, numbers and underscores."}`

##### EXPECTED RESULTS
Your role should work. Moreover you should have tests so that users don't need to report such bugs.

##### ACTUAL RESULTS
Already provided
