### ISSUE TITLE
Comparison to literal Bool should be fixed

### ISSUE THREAD

**Issue by kharkevich** [lean-delivery/ansible-role-oracle-db#5]
##### SUMMARY

Broken E601 from Ansible Galaxy (https://github.com/ansible/galaxy-lint-rules/blob/master/rules/ComparisonToLiteralBoolRule.py)
##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE

Broken files
tasks/oraInst/checkOraInst.yml
tasks/main.yml
tasks/system/swap.yml

```yaml
    - name: "Create swapfile"
      command: "dd if=/dev/zero of={{ oracledb.swapfile_path }} \
        bs={{ oracledb.swapfile_bs_size_mb }}M \
        count={{ oracledb.swapfile_count }}"
      when: swapfile.stat.exists == False
```

##### EXPECTED RESULTS

```yaml
    - name: "Create swapfile"
      command: "dd if=/dev/zero of={{ oracledb.swapfile_path }} \
        bs={{ oracledb.swapfile_bs_size_mb }}M \
        count={{ oracledb.swapfile_count }}"
      when: not swapfile.stat.exists
```
